* execnik

** author info: Jacek Podkanski

This is a project to demonstrate ability of creation cross-platform Gtk
applications in SBCL.

** License

Public Domain

** interesting links

https://github.com/plops/cl-cffi-gtk-from-repl

** Usage

*** REPL

Add directory with the project as in the following example

#+BEGIN_SRC lisp
  (push #p "c:/Users/Jacek/Documents/Programming/Lisp/execnik/" asdf:*central-registry*)
  (ql:quickload :execnik)
  (in-package :execnik)
#+END_SRC

*** compilation and running

#+BEGIN_EXAMPLE
sbcl --load ./compilation.lisp
./execnik.exe
#+END_EXAMPLE

**** Running on Linux

On Linux it works in terminal and file managers.

**** Runnning on Windows

It also works in File Explorer on Windows if you have Msys2 and gtk libraries
installed and ~C:\msys64\mingw64\bin~ path added to your environment variables.

If you do not have the ~mingw64\bin~ path added to your environment you need to
start Msys2 terminal, cd to the executable and start it from the terminal.

*** Distribution of binary on Windows

**** suggested solution

Ideal solution would be creation of distributable package similar to:
https://github.com/msys2/msys2/wiki/Distributing

**** Styrene

I decided to try Styrene

https://github.com/achadwick/styrene

***** cfg file

Next, I have created ~execnik.cfg~ file, which will be used to compile a Windows
installer. As a template I used ~gtk3-examples.cfg~ copied from styrene
repository.

***** building

I started Msys2 terminal entered styrene folder and ran:

#+BEGIN_EXAMPLE
./styrene.sh -o ./tmp/ /c/Users/Jacek/Documents/Programming/Lisp/execnik/execnik.cfg
#+END_EXAMPLE

That has lead to realization that I need to create a pacman package first.

******  possible clue
 https://blogs.gnome.org/nacho/2014/08/01/how-to-build-your-gtk-application-on-windows/

****** cont

install build packages for msys2
https://github.com/msys2/MSYS2-packages

creating packages
https://github.com/msys2/msys2/wiki/Creating-Packages

Native Windows software (from this project's perspective) is software that
doesn't depend on msys-2.0.dll, and links dynamically to the highly compatible
~msvcrt.dll.~



***** Another experiment

Creating distribution folder, copying bin and shared folders from mingw64 and
copying my executable to bin creates bloated folder that can be possibly
distributed.

So now we need to figure out how to copy only the files we need and create a
decent installer.

***** bundling libraries myself

Downloading listdlls from
https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls
and copying executable ~Listdlls64.exe~
to c:/Users/Jacek/AppData/Roaming/local/bin/Listdlls64.exe
has revealed sources of used libraries

now I can run
#+BEGIN_EXAMPLE
Listdlls64.exe execnik.exe | grep msys
#+END_EXAMPLE
to reveal paths to loaded libraries
